[@ww.textfield labelKey="octopus.serverUrl.key" name="serverUrl" required='true'/]
<div class="description">[@s.text name='octopus.serverUrl.help' /]</div>
[@ww.password labelKey="octopus.apiKey.key" name="apiKey" required='true' showPassword='true'/]
<div class="description">[@s.text name='octopus.apiKey.help' /]</div>
[@ww.textfield labelKey="octopus.projectName.key" name="projectName" required='true'/]
<div class="description">[@s.text name='octopus.projectName.help' /]</div>
[@ww.textfield labelKey="octopus.releaseVersion.key" name="releaseVersion" required='false'/]
<div class="description">[@s.text name='octopus.releaseVersion.help' /]</div>
[@ww.textfield labelKey="octopus.channelName.key" name="channelName" required='false'/]
<div class="description">[@s.text name='octopus.channelName.help' /]</div>
[@ww.textfield labelKey="octopus.environmentName.key" name="environmentName" required='false'/]
<div class="description">[@s.text name='octopus.environmentName.help' /]</div>
[@ww.textfield labelKey="octopus.tenants.key" name="tenants" required='false'/]
<div class="description">[@s.text name='octopus.tenants.help' /]</div>
<div class="description">[@s.text name='octopus.tenants.help2' /]</div>
[@ww.textfield labelKey="octopus.tenantTags.key" name="tenantTags" required='false'/]
<div class="description">[@s.text name='octopus.tenantTags.help' /]</div>
<div class="description">[@s.text name='octopus.tenantTags.help2' /]</div>
[@ww.checkbox labelKey="octopus.showProgress.key" name="showProgress" required='false'/]
<div class="description">[@s.text name='octopus.showProgress.help' /]</div>
[@ww.checkbox labelKey="octopus.ignoreExisting.key" name="ignoreExisting" required='false'/]
<div class="description">[@s.text name='octopus.ignoreExisting.help' /]</div>
[@ww.checkbox labelKey="octopus.verboseLogging.key" name="verboseLogging" required='false'/]
[@ww.textfield labelKey="octopus.additionalArgs.key" name="additionalArgs" required='false'/]
<div class="description">[@s.text name='octopus.additionalArgs.help' /]</div>
