[@ww.textfield labelKey="octopus.serverUrl.key" name="serverUrl" required='true'/]
[@ww.password labelKey="octopus.apiKey.key" name="apiKey" required='true' showPassword='true'/]
[@ww.textfield labelKey="octopus.projectName.key" name="projectName" required='true'/]
[@ww.textfield labelKey="octopus.environmentName.key" name="environmentName" required='true'/]
[@ww.textfield labelKey="octopus.releaseVersion.key" name="releaseVersion" required='true'/]
[@ww.textfield labelKey="octopus.tenants.key" name="tenants" required='false'/]
[@ww.textfield labelKey="octopus.tenantTags.key" name="tenantTags" required='false'/]
[@ww.checkbox labelKey="octopus.showProgress.key" name="showProgress" required='false'/]
[@ww.checkbox labelKey="octopus.verboseLogging.key" name="verboseLogging" required='false'/]
[@ww.textfield labelKey="octopus.additionalArgs.key" name="additionalArgs" required='false'/]
