[@ww.textfield labelKey="octopus.serverUrl.key" name="serverUrl" required='true'/]
[@ww.password labelKey="octopus.apiKey.key" name="apiKey" required='true' showPassword='true'/]
[@ww.textfield labelKey="octopus.pushPattern.key" name="pushPattern" required='true'/]
[@ww.checkbox labelKey="octopus.force.key" name="force" required='false'/]
[@ww.checkbox labelKey="octopus.verboseLogging.key" name="verboseLogging" required='false'/]