name: 'Bamboo compatibility update check'

on:
  schedule:
    # Monday 8am AEST (Sunday 10pm UTC)
    - cron: '0 22 * * 0'

  workflow_dispatch:

env:
  GH_TOKEN: ${{ secrets.BAMBOO_GITHUB_ACTIONS_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.BAMBOO_GITHUB_ACTIONS_TOKEN }}

jobs:
  check-for-update:
    name: 'Check for new version'
    runs-on: 'ubuntu-latest'

    outputs:
      update-available: ${{ steps.version-check.outputs.update-available }}
      compatible-version: ${{ steps.version-check.outputs.current-compatible-version }}
      bamboo-version: ${{ steps.version-check.outputs.latest-bamboo-version }}
      gh-issue-url: ${{ steps.create-issue.outputs.issue-url }}

    steps:
      - uses: actions/checkout@v3

      - name: 'Check for new version of Bamboo'
        id: version-check
        run: |
          # get the version our plugin is compatible with
          currentCompatibleVersion=$(curl -sS -X GET https://marketplace.atlassian.com/rest/2/addons/com.octopus.bamboo/versions/latest | jq '.compatibilities[0].hosting.server.max.version')
          echo $currentCompatibleVersion
          # get latest available version of Bamboo
          latestBambooVersion=$(curl -sS -X GET https://marketplace.atlassian.com/rest/2/products/key/bamboo/versions/latest | jq '.name')
          echo $latestBambooVersion
          echo "::set-output name=update-available::true"
          echo "::set-output name=current-compatible-version::$currentCompatibleVersion"
          echo "::set-output name=latest-bamboo-version::$latestBambooVersion"

  create-issue:
    name: 'Create issue'
    runs-on: 'ubuntu-latest'

    needs: check-for-update
    if: ${{ needs.check-for-update.outputs.update-available }}

    outputs:
      gh-issue-url: ${{ steps.create-issue.outputs.issue-url }}

    steps:
      - uses: actions/checkout@v3

      - name: 'Create Issue for new Bamboo version'
        id: create-issue
        run: |
          compatibleBambooVersion=${{ needs.check-for-update.outputs.compatible-version }}
          latestBambooVersion=${{ needs.check-for-update.outputs.bamboo-version }}
          
          issueTitle="Add-on Update Request: Support for new Bamboo version"
          issueBody=$(cat << EOF
          ## Add-on compatibility update
          - **Compatible Bamboo version:** \`$compatibleBambooVersion\`
          - **New Bamboo version:** \`$latestBambooVersion\`
          EOF
          )
          # create issue and assign it to @team-integrations-fnm-bot
          issueUrl=$(gh issue create --title "$issueTitle" --body "$issueBody" --assignee "@me")
          echo $issueUrl
          echo "::set-output name=issue-url::$issueUrl"

  update-pom:
    name: 'Update POM.xml'
    runs-on: 'ubuntu-latest'

    needs: [check-for-update, create-issue]
    if: ${{ needs.create-issue.outputs.gh-issue-url != '' }}

    outputs:
      changes-committed: ${{ steps.commit-pom-update.outputs.changes-committed }}
      branch: ${{ steps.commit-pom-update.outputs.branch-name }}

    steps:
      - uses: actions/checkout@v3

      - name: 'Update Bamboo version in POM.xml and commit the changes'
        id: commit-pom-update
        run: |
          bambooVersion="${{ needs.check-for-update.outputs.bamboo-version }}"
          branchName="team-integrations-fnm-bot/bamboo-$bambooVersion"
          
          git config --global user.name "team-integrations-fnm-bot"
          git config --global user.email "integrationsfnmbot@octopus.com"
          git checkout -b $branchName
          
          # Update the version in the <bamboo.version> and <bamboo.data.version> properties
          sed -i "s/\(^.*<bamboo\(.data\)\?.version>\).*\(<\/bamboo\(.data\)\?.version>.*$\)/\1$bambooVersion\3/g" pom.xml

          git add pom.xml
          # if no changes were made, just silently exit
          git diff-index --quiet HEAD || (git commit -m "fix: update compatible bamboo version" \
            && git push -u origin $branchName \
            && echo "::set-output name=changes-committed::true" \
            && echo "::set-output name=branch-name::$branchName" \
          )          

  create-pull-request:
    name: 'Create PR'
    runs-on: 'ubuntu-latest'

    needs: [check-for-update, create-issue, update-pom]
    if: ${{ needs.update-pom.outputs.changes-committed }}

    steps:
      - uses: actions/checkout@v3

      - name: 'Create PR to update Bamboo version in POM.xml'
        run: |
          title="Add compatibility for Bamboo version ${{ needs.check-for-update.outputs.bamboo-version }}"
          body="Fixes ${{ needs.create-issue.outputs.gh-issue-url }}"
          head="${{ needs.update-pom.outputs.branch }}"
          
          gh pr create --title "$title" --body "$body" --base "main" --head "$head"
