on:
  push:
    branches:
      - main
name: release-please
permissions:
  contents: write
  pull-requests: write
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: simple
          token: ${{ secrets.BAMBOO_GITHUB_ACTIONS_TOKEN }}
